package RogueLite.characters.skills;

public enum TargetType {
  SELF,
  ALLY_SINGLE,
  ALLY_SINGLE_LOWEST_HP,
  ALLY_SINGLE_HIGHEST_HP,
  ALLY_MULTI_TARGET,
  ALLY_TEAM,
  ENNEMY_SINGLE,
  ENNEMY_SINGLE_LOWEST_HP,
  ENNEMY_SINGLE_HIGHEST_HP,
  ENNEMY_MULTI_TARGET,
  ENNEMY_TEAM,
  ALL
}
